---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app

# SOURCE: https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/#limitlabelsandannotationstospecificresourcesorfields
labels:
- pairs:
    monitoring: prometheus
    prometheus: main

# commonAnnotations:
#   argocd.argoproj.io/sync-wave: "-10"


patches:
- target:
    kind: Job
    name: ingress-nginx-admission-create
  # Strip
  # Stripping is specified by the "-"" chomping indicator. In this case, the final line break and any trailing empty lines are excluded from the scalar's content.
  patch: |-
    - path: "/spec/ttlSecondsAfterFinished"
      op: remove


helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.9.0
  releaseName: ingress-nginx
  namespace: kube-system
  includeCRDs: true
