---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app

# SOURCE: https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/#limitlabelsandannotationstospecificresourcesorfields
labels:
- pairs:
    monitoring: prometheus
    prometheus: main

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.13.2
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesFile: app/values.yaml
