---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/default/authelia
spec:
  project: cluster
  sources:
  - repoURL: 'https://bjw-s.github.io/helm-charts'
    chart: app-template
    targetRevision: 2.5.0
    helm:
      valueFiles:
        - $values/kubernetes/apps/default/authelia/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: main
    path: kubernetes/apps/default/authelia
    ref: values
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
