---
fail_fast: false
repos:
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.26.1
  #   hooks:
  #     - args:
  #         - --config-file
  #         - .github/lint/.yamllint.yaml
  #       id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
    exclude: ^*s-vault-token.yaml$
  # # "repo: local" is a configuration in the pre-commit file that specifies the location of a local repository that contains custom hooks. The "language" key is set to "script" to indicate that the hook is implemented as a shell script, something like this
  # - repo: local
  #   hooks:
  #   - id: unencrypted-detection
  #     language: script
  #     name: unencrypted-detection
  #     entry: ./git_hooks/unencrypted-detection
  #     stage: [commit]
# #################################################
# diademiemi/homelab
# ---
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.4.0
#     hooks:
#       - id: trailing-whitespace
#         args: [--markdown-linebreak-ext=md]
#       - id: end-of-file-fixer
#       - id: check-added-large-files
#       - id: check-yaml
#         files: .*\.(yaml|yml)$
#         args: [--unsafe]
#       - id: check-json
#       - id: check-xml
#       - id: check-toml
#       - id: check-case-conflict
#       - id: check-merge-conflict
#       - id: detect-private-key
#       - id: check-shebang-scripts-are-executable
#       - id: check-executables-have-shebangs
#       - id: check-added-large-files

#   - repo: https://github.com/ansible/ansible-lint
#     rev: v6.17.0
#     hooks:
#       - id: ansible-lint
#         files: \.(yaml|yml)$
#         entry: sh -c 'python3 -m pip install -r requirements.txt; python3 -m ansiblelint -v --force-color'

# ...
