---
creation_rules:
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  # - path_regex: kubernetes/apps/default/authelia/config/.*\.sops\.y?ml
  #   key_groups:
  #     - age:
  #         - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: kubernetes/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: apps/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
  - path_regex: infra/.*\.sops\.yaml
    key_groups:
      - age:
          - age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
