---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- k8s-rbac-prometheus-k8s.yaml
- app.yaml
- argocd-metrics-servicemonitor.yaml
- argocd-server-metrics-servicemonitor.yaml
- argocd-repo-server-metrics-servicemonitor.yaml
- argocd-notifications-controller-metrics-servicemonitor.yaml
