apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get # supports viewing live object manifest in UI
  - list
  - watch
  - update
  - patch # supports `argocd app patch`
  - delete # supports deletion a live object in UI
#########################################################
# SOURCE: https://github.com/argoproj/argo-cd/blob/master/manifests/cluster-rbac/server/argocd-server-clusterrole.yaml
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list    # supports listing events in UI
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  verbs:
  - get     # supports viewing pod logs from UI
  - create     # supports viewing pod logs from UI
- apiGroups:
  - "argoproj.io"
  resources:
  - "applications"
  - "applicationsets"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create   # supports triggering jobs from UI
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create   # supports triggering workflows from UI
# work
# - apiGroups:
#   - '*'
#   resources:
#   - '*'
#   verbs:
#   - delete
#   - get
#   - patch
# - apiGroups:
#   - ""
#   resources:
#   - events
#   verbs:
#   - list
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - pods/log
#   verbs:
#   - get
# - apiGroups:
#   - argoproj.io
#   resources:
#   - applications
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - batch
#   resources:
#   - jobs
#   verbs:
#   - create
# - apiGroups:
#   - argoproj.io
#   resources:
#   - workflows
#   verbs:
#   - create
