$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: argocd-applicationset-controller-network-policy
  namespace: argocd
