apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  $patch: merge
  helm.valuesFileSchemes: >-
    secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import, secrets+age-import-kubernetes, secrets,secrets+literal, https
