kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: pdb-argocd-application-controller
  namespace: argocd
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
