# NOTE: this PDB is currently not useful as replicas: 1
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: pdb-argocd-notifications-controller
  namespace: argocd
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
