# NOTE: this PDB is currently not useful as replicas: 1
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: argocd-dex-server
  namespace: argocd
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
