---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app


# commonAnnotations:
#   argocd.argoproj.io/sync-options: Replace=true

# SOURCE: https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/#limitlabelsandannotationstospecificresourcesorfields
labels:
- pairs:
    monitoring: prometheus
    prometheus: main

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-50"


patches:
# NOTE: https://github.com/argoproj/argo-cd/issues/6880
- target:
    kind: Job
    name: thanos-minio-post-job
    # loki-minio-make-bucket-job
    # k batch/Job/ingress-nginx-admission-create
  # Strip
  # Stripping is specified by the "-"" chomping indicator. In this case, the final line break and any trailing empty lines are excluded from the scalar's content.
  patch: |-
    - path: "/spec/ttlSecondsAfterFinished"
      op: remove

- target:
    kind: Job
    name: loki-minio-make-bucket-job
  patch: |-
    - path: "/spec/ttlSecondsAfterFinished"
      op: remove

- target:
    kind: Job
    name: kube-prometheus-stack-admission-create
  patch: |-
    - path: "/spec/ttlSecondsAfterFinished"
      op: remove

- target:
    kind: Job
    name: kube-prometheus-stack-admission-patch
  patch: |-
    - path: "/spec/ttlSecondsAfterFinished"
      op: remove
