---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app


# commonAnnotations:
#   argocd.argoproj.io/sync-options: Replace=true

# SOURCE: https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/#limitlabelsandannotationstospecificresourcesorfields
labels:
- pairs:
    monitoring: prometheus
    prometheus: main
