# helm repo add k8s-ephemeral-storage-metrics https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart
# helm repo update
# helm upgrade --install my-deployment k8s-ephemeral-storage-metrics/k8s-ephemeral-storage-metrics
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  sources:
  - repoURL: 'https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart'
    chart: k8s-ephemeral-storage-metrics
    targetRevision: 1.5.2
    helm:
      releaseName: k8s-ephemeral-storage-metrics
      valueFiles:
        - $values/apps/argocd/base/monitoring/k8s-ephemeral-storage-metrics/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground.git'
    targetRevision: HEAD
    path: apps/argocd/base/monitoring/k8s-ephemeral-storage-metrics
    ref: values
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
      # Needed because our kubectl apply exceeds thresholds
      # EXAMPLE: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
      # SOURCE: https://github.com/prometheus-operator/prometheus-operator/issues/4355
      - ServerSideApply=true

    # NOTE: 2/12/2024 - IF THIS BREAKS, CONFIGURE IN THESE VALUES AND COMMENT OUT THE OTHER RETRY BLOCK
    # retry:
    #   limit: -1  # Max number of allowed sync retries
    #   backoff:
    #     duration: 20s # Retry backoff base duration. Input needs to be a duration (e.g. 2m, 1h) (default 5s)
    #     factor: 2 # Factor multiplies the base duration after each failed retry (default 2)
    #     maxDuration: 15m # Max retry backoff duration. Input needs to be a duration (e.g. 2m, 1h) (default 3m0s)
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
  # SOURCE: https://github.com/home-prod/k8s-infra/blob/82cbe52ba47597b52a7fc03eee4d1b526beab836/kubernetes/charts/infra/charts/logging/charts/k8s-ephemeral-storage-metrics/templates/k8s-ephemeral-storage-metrics-application.yaml#L32
  ignoreDifferences:
  - group: apps
    kind: DaemonSet
    jsonPointers:
      - /metadata/annotations
  - kind: PersistentVolume
    jsonPointers:
      - /spec/claimRef/resourceVersion
      - /spec/claimRef/uid
      - /status/lastPhaseTransitionTime
