---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  sources:
  - repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
    chart: metrics-server
    targetRevision: 3.11.0
    helm:
      valueFiles:
        - $values/apps/argocd/base/monitoring/metrics-server/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground.git'
    targetRevision: main
    path: apps/argocd/base/monitoring/metrics-server
    ref: values
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
