---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/kube-system/multus
spec:
  project: cluster
  sources:
  - repoURL: 'https://angelnu.github.io/helm-charts'
    chart: multus
    targetRevision: 5.0.4
    helm:
      releaseName: multus
      valueFiles:
        - $values/kubernetes/apps/kube-system/multus/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: HEAD
    path: kubernetes/apps/kube-system/multus
    ref: values
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
