apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    # SOURCE: https://github.com/rdartus/k3s-argo/blob/main/jeanKluster/templates/traefik.yml
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-10"
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/bossjones/k3d-playground'
    path: apps/argocd
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      # SOURCE: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
      # By default (and as a safety mechanism), automated sync will not delete resources when Argo CD detects the resource is no longer defined in Git. To prune the resources, a manual sync can always be performed (with pruning checked).
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    # By default, extraneous resources get pruned using foreground deletion policy. The propagation policy can be controlled using PrunePropagationPolicy sync option. Supported policies are background, foreground and orphan. More information about those policies could be found here.
    - PrunePropagationPolicy=foreground
    # This feature is to allow the ability for resource pruning to happen as a final, implicit wave of a sync operation, after the other resources have been deployed and become healthy, and after all other waves completed successfully.
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
  # SOURCE: https://github.com/argoproj/argo-cd/issues/11074
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .spec.endpoints[]?.relabelings[]?.action
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .spec.endpoints[]?.metricRelabelings[]?.action
