# yaml-language-server: $schema=https://raw.githubusercontent.com/bossjones/k3d-playground/main/schema/external-secrets/v0.9.11/externalsecret_v1beta1.json
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argocd-sops-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          # if the binary is in your PATH, you can do
          path: ksops
files:
  - age.sops.yaml
  # - sso.sops.yaml
