---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secrets
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: pgadmin-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      # Use inline templates to construct your desired config file that contains your secret
      data:
        POSTGRES_SUPER_USER: "authentik"
        POSTGRES_SUPER_PASS: "8edF6sRQjx"
        AWS_ACCESS_KEY_ID: "admin"
        AWS_SECRET_ACCESS_KEY: "password"
        username: "authentik"
        password: "8edF6sRQjx"
        PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
        PGADMIN_DEFAULT_PASSWORD: "8edF6sRQjx"
  # dataFrom:
  #   - find:
  #       name:
  #         regexp: .*
  dataFrom:
  - find:
      # path: path/to/my
      name:
        regexp: .*
