---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: databases
resources:
  - app.yaml
  - pvc.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: servers-json
    files:
      - config/servers.json
generatorOptions:
  disableNameSuffixHash: true
  # annotations:
  #   kustomize.toolkit.fluxcd.io/substitute: disabled
