apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"applicationset-controller","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-applicationset-controller","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-applicationset-controller","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-applicationset-controller"},"subjects":[{"kind":"ServiceAccount","name":"argocd-applicationset-controller","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-applicationset-controller
    namespace: argocd
    resourceVersion: "101757"
    uid: 8ff37cae-4f6f-478d-bbb4-7b6ad55a4097
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-applicationset-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-server-extensions","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-server-extensions"},"subjects":[{"kind":"ServiceAccount","name":"argocd-server","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-server-extensions
    namespace: argocd
    resourceVersion: "101758"
    uid: bbfb6c8e-f3b8-4d64-bbe4-578d2157e70f
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-server-extensions
  subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-notifications-controller","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-notifications-controller"},"subjects":[{"kind":"ServiceAccount","name":"argocd-notifications-controller","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "101759"
    uid: fe05283e-e5c8-4cb4-ad50-1165adfe8caf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-notifications-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"dex-server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-dex-server","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-dex-server","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-dex-server"},"subjects":[{"kind":"ServiceAccount","name":"argocd-dex-server","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-dex-server
    namespace: argocd
    resourceVersion: "101760"
    uid: 64ca4ede-1297-42bd-a4ec-8ce5870660b2
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-dex-server
  subjects:
  - kind: ServiceAccount
    name: argocd-dex-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-server","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-server"},"subjects":[{"kind":"ServiceAccount","name":"argocd-server","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-server
    namespace: argocd
    resourceVersion: "101761"
    uid: b75e1d2d-b72d-469a-bc8a-476e09d18021
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-server
  subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{"reloader.stakater.com/auto":"true"},"labels":{"app.kubernetes.io/component":"application-controller","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-application-controller","app.kubernetes.io/part-of":"argocd","monitoring":"prometheus","prometheus":"main"},"name":"argocd-application-controller","namespace":"argocd"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"argocd-application-controller"},"subjects":[{"kind":"ServiceAccount","name":"argocd-application-controller","namespace":"argocd"}]}
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:28:49Z"
    labels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
      monitoring: prometheus
      prometheus: main
    name: argocd-application-controller
    namespace: argocd
    resourceVersion: "101762"
    uid: 75510c28-9d1d-4964-bd18-a859c0add36f
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-application-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
kind: List
metadata:
  resourceVersion: ""
