apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2024-01-27T03:29:44Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      monitoring: prometheus
      prometheus: main
    name: prometheus-k8s
    namespace: monitoring
    resourceVersion: "1576"
    uid: 8efa7830-10e5-46ba-8717-054cc33e1b4e
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:29:44Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 10.2.3
      helm.sh/chart: grafana-7.2.4
    name: kube-prometheus-stack-grafana
    namespace: monitoring
    resourceVersion: "125052"
    uid: c2df8e6e-8b29-49cb-bcd3-af2b441e58b7
  rules: null
kind: List
metadata:
  resourceVersion: ""
