apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2024-01-27T03:29:44Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      monitoring: prometheus
      prometheus: main
    name: prometheus-k8s-config
    namespace: monitoring
    resourceVersion: "1580"
    uid: baf2cfd3-ad92-4b92-8f3a-cc21a4b1bb19
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s-config
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      reloader.stakater.com/auto: "true"
    creationTimestamp: "2024-01-27T03:29:44Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 10.2.3
      helm.sh/chart: grafana-7.2.4
    name: kube-prometheus-stack-grafana
    namespace: monitoring
    resourceVersion: "76653"
    uid: 1df7ab4c-37cd-4b74-8c85-7db0c4697497
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kube-prometheus-stack-grafana
  subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-grafana
    namespace: monitoring
kind: List
metadata:
  resourceVersion: ""
