---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/database/cloudnative-pg
spec:
  project: cluster
  sources:
  - repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    targetRevision: 0.20.0
    helm:
      valueFiles:
        - $values/kubernetes/apps/database/cloudnative-pg/app/operator/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: main
    path: kubernetes/apps/database/cloudnative-pg
    ref: values
  destination:
    name: in-cluster
    namespace: database
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
