---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /apps/argocd/base/database/cloudnative-pg
spec:
  project: cluster
  sources:
  - repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    targetRevision: 0.20.1
    helm:
      releaseName: cloudnative-pg
      valueFiles:
        - $values/apps/argocd/base/database/cloudnative-pg/app/operator/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: HEAD
    path: apps/argocd/base/database/cloudnative-pg
    ref: values
  destination:
    name: in-cluster
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
      # Needed because our kubectl apply exceeds thresholds
      # EXAMPLE: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
      # SOURCE: https://github.com/prometheus-operator/prometheus-operator/issues/4355
      - ServerSideApply=true
      - Prune=true
      - Validate=false
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
  # SOURCE: https://github.com/argoproj/argo-cd/issues/11074
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .spec.endpoints[]?.relabelings[]?.action
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .spec.endpoints[]?.metricRelabelings[]?.action
    # SOURCE: https://github.com/home-prod/k8s-infra/blob/82cbe52ba47597b52a7fc03eee4d1b526beab836/kubernetes/charts/infra/charts/monitoring/charts/kube-prometheus-stack/templates/kube-prometheus-stack-application.yaml
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
    - kind: PersistentVolume
      jsonPointers:
        - /spec/claimRef/resourceVersion
        - /spec/claimRef/uid
        - /status/lastPhaseTransitionTime
    # SOURCE: https://github.com/rogerrum/k8s-gitops/blob/578d7a8cdd89dd940060e005942e567814dcf9f6/main/monitoring/values.yaml#L24
    # SOURCE: https://github.com/search?q=jqpathexpressions+metricRelabelings&type=code
    # - kind: MutatingWebhookConfiguration
    #   jsonPointers:
    #     - /webhooks/0/failurePolicy
    # - kind: ValidatingWebhookConfiguration
    #   jsonPointers:
    #     - /webhooks/0/failurePolicy
    # - kind: ServiceAccount
    #   jsonPointers:
    #     - /imagePullSecrets
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - '.spec.data[].remoteRef.conversionStrategy'
        - '.spec.data[].remoteRef.decodingStrategy'
        - '.spec.data[].remoteRef.metadataPolicy'
        - '.spec.dataFrom[].extract.conversionStrategy'
        - '.spec.dataFrom[].extract.decodingStrategy'
        - '.spec.dataFrom[].extract.metadataPolicy'
# - name: blackbox-exporter
#   namespace: monitoring
#   path: main/monitoring/blackbox-exporter
#   manifest-paths: /main/monitoring/blackbox-exporter
#   sync-wave: "-1"
#   ignoreDifferences:
#     - group: "*"
#       kind: "ServiceMonitor"
#       jqPathExpressions:
#         - .spec.endpoints[].metricRelabelings
#   helm:
#     enabled: true
#   syncOptions:
#     - RespectIgnoreDifferences=true
