---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio
  - app.yaml
  - cluster/cluster.yaml
  - cluster/externalSecret.yaml
  - cluster/prometheusRule.yaml
  - cluster/scheduledbackup.yaml
  - cluster/service.yaml
