---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio
  - app.yaml
  - cluster/cluster.yaml
  - cluster/externalSecret.yaml
  - cluster/prometheusRule.yaml
  - cluster/scheduledbackup.yaml
  - cluster/service.yaml
  - cluster/deployment_psql.yaml
  # - cluster/pg-dashboard.yaml
  - cluster/pg-ingress.yaml

configMapGenerator:
  - name: cloudnative-pg-dashboard
    files:
      - cloudnative-pg-dashboard.json=https://raw.githubusercontent.com/cloudnative-pg/charts/cloudnative-pg-v0.16.0/charts/cnpg-sandbox/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
