apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-10"
  name: metallb-pool
  namespace: metallb
spec:
  addresses:
  - "192.168.1.4-192.168.1.5"