apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
spec:
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.35.0
          # 2/19/2024  - https://argo-workflows.readthedocs.io/en/latest/argo-server-sso-argocd/
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-server-sso
                  key: clientSecret
          args:
            - dex
            - serve
            - /data/config.yaml
          ports:
            - name: http
              containerPort: 5556
          volumeMounts:
            - name: dex-ssl
              mountPath: /etc/dex/ssl
              readOnly: true
            - mountPath: /data
              name: config
      volumes:
        - name: config
          configMap:
            name: dex
        - name: dex-ssl
          secret:
            secretName: tls-secret
