apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
  # - db.yaml
  - github.com/rancher/local-path-provisioner/examples/pvc

namespace: example
