---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  sources:
  - repoURL: 'https://helm.vector.dev'
    chart: vector
    targetRevision: 0.30.0
    helm:
      releaseName: vector
      valueFiles:
        - $values/apps/argocd/base/monitoring/vector/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground.git'
    targetRevision: main
    path: apps/argocd/base/monitoring/vector
    ref: values
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      # selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Needed because our kubectl apply exceeds thresholds
      # EXAMPLE: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
      # SOURCE: https://github.com/prometheus-operator/prometheus-operator/issues/4355
      - ServerSideApply=true
