---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: authentik-secret # name of the k8s Secret to be created
  data:
  - secretKey: Authentik
    remoteRef:
      key: secret/authentik/authentik
      metadataPolicy: Fetch
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: authentik-db # name of the k8s Secret to be created
  data:
  - secretKey: AuthentikDB
    remoteRef:
      key: secret/authentik/authentik-db
      metadataPolicy: Fetch
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: authentik-db-secret # name of the k8s Secret to be created
  data:
  - secretKey: AuthentikDB
    remoteRef:
      key: secret/authentik/authentik-db-secret
      metadataPolicy: Fetch
