apiVersion: v1
kind: Secret
metadata:
  name: authentik
stringData:
  Authentik: "{\"AUTHENTIK_SECRET_KEY\": \"password\",\"AUTHENTIK_EMAIL__HOST\": \"k8s.localhost\",\"AUTHENTIK_EMAIL__USERNAME\": \"admin\",\"AUTHENTIK_EMAIL__PASSWORD\": \"password\",\"AUTHENTIK_EMAIL__FROM\": \"admin@k8s.localhost\"}" # Needs to be a JSON
  # source-key2: bar  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-pushsecret
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik
  data:
    - match:
        secretKey: Authentik
        remoteRef:
          remoteKey: authentik/authentik

---
################################################################################################
#  next
################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: authentik-db
stringData:
  AuthentikDB: "{\"AUTHENTIK_POSTGRESQL__HOST\": \"postgres-rw.databases.svc.cluster.local\",  \"AUTHENTIK_POSTGRESQL__NAME\": \"authentik\",  \"AUTHENTIK_POSTGRESQL__PASSWORD\": \"8edF6sRQjx\",  \"AUTHENTIK_POSTGRESQL__SSLMODE\": \"disable\",  \"AUTHENTIK_POSTGRESQL__USE_PGBOUNCER\": \"false\",  \"AUTHENTIK_POSTGRESQL__USER\": \"authentik\",  \"AWS_ACCESS_KEY_ID\": \"admin\",  \"AWS_SECRET_ACCESS_KEY\": \"password\",  \"INIT_POSTGRES_DBNAME\": \"authentik\",  \"INIT_POSTGRES_HOST\": \"postgres-rw.databases.svc.cluster.local\",  \"INIT_POSTGRES_PASS\": \"password\",  \"INIT_POSTGRES_SUPER_PASS\": \"password\",  \"INIT_POSTGRES_USER\": \"postgres\",  \"POSTGRES_SUPER_PASS\": \"8edF6sRQjx\",  \"POSTGRES_SUPER_USER\": \"authentik\"}" # Needs to be a JSON
  # source-key2: bar  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-db-pushsecret
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-db
  data:
    - match:
        secretKey: AuthentikDB
        remoteRef:
          remoteKey: authentik/authentik-db

---
################################################################################################
#  next
################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: authentik-db-secret
stringData:
  AuthentikDBSecret: "{\"AUTHENTIK_EMAIL__FROM\": \"admin@k8s.localhost\",  \"AUTHENTIK_EMAIL__HOST\": \"k8s.localhost\",  \"AUTHENTIK_EMAIL__PASSWORD\": \"password\",  \"AUTHENTIK_EMAIL__PORT\": \"465\",  \"AUTHENTIK_EMAIL__USE_TLS\": \"true\",  \"AUTHENTIK_EMAIL__USERNAME\": \"admin@k8s.localhost\",  \"AUTHENTIK_POSTGRESQL__HOST\": \"postgres-rw.databases.svc.cluster.local\",  \"AUTHENTIK_POSTGRESQL__NAME\": \"authentik\",  \"AUTHENTIK_POSTGRESQL__PASSWORD\": \"password\",  \"AUTHENTIK_POSTGRESQL__SSLMODE\": \"disable\",  \"AUTHENTIK_POSTGRESQL__USE_PGBOUNCER\": \"false\",  \"AUTHENTIK_POSTGRESQL__USER\": \"postgres\",  \"INIT_POSTGRES_DBNAME\": \"authentik\",  \"INIT_POSTGRES_HOST\": \"postgres-rw.databases.svc.cluster.local\",  \"INIT_POSTGRES_PASS\": \"password\",  \"INIT_POSTGRES_SUPER_PASS\": \"password\",  \"INIT_POSTGRES_USER\": \"postgres\"}" # Needs to be a JSON
  # source-key2: bar  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-db-secret-pushsecret
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-db-secret
  data:
    - match:
        secretKey: AuthentikDB
        remoteRef:
          remoteKey: authentik/authentik-db-secret
