---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/database/redis
spec:
  project: cluster
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: 18.8.0
    helm:
      valueFiles:
        - $values/kubernetes/apps/database/redis/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: HEAD
    path: kubernetes/apps/database/redis
    ref: values
  destination:
    name: in-cluster
    namespace: database
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
