# yaml-language-server: $schema=https://raw.githubusercontent.com/bossjones/k3d-playground/main/schema/argocd/v2.8.0/appproject_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster-wide project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
