# yaml-language-server: $schema=https://raw.githubusercontent.com/bossjones/k3d-playground/main/schema/argocd/v2.8.0/appproject_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Core Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
