controllers:
  main:
    annotations:
      secret.reloader.stakater.com/reload: authentik-redis-secret

    pod:
      automountServiceAccountToken: false

    containers:
      main:
        image:
          repository: public.ecr.aws/docker/library/redis
          tag: 7.2.4
        command:
          - sh
        args:
          - -c
          - >-
            redis-server --requirepass $REDIS_PASSWORD
        env:
          REDIS_PORT: 6379
          REDIS_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: authentik-redis-secret
                key: AUTHENTIK_REDIS_PASSWORD
        resources:
          requests:
            cpu: 5m
            memory: 128M
          limits:
            memory: 256M

service:
  main:
    ports:
      http:
        enabled: false
      redis:
        enabled: true
        port: 6379
