---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/argoproj/argo-rollouts'
    targetRevision: v1.6.4
    path: manifests/cluster-install
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # NOTE: 2/12/2024 - IF THIS BREAKS, CONFIGURE IN THESE VALUES AND COMMENT OUT THE OTHER RETRY BLOCK
    retry:
      limit: -1  # Max number of allowed sync retries
      backoff:
        duration: 20s # Retry backoff base duration. Input needs to be a duration (e.g. 2m, 1h) (default 5s)
        factor: 2 # Factor multiplies the base duration after each failed retry (default 2)
        maxDuration: 3m # Max retry backoff duration. Input needs to be a duration (e.g. 2m, 1h) (default 3m0s)
    # retry:
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m0s
    #   limit: 2
