apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo
servers: 1
agents: 2
kubeAPI:
  host: "k8s.localhost"
  # hostIP: "127.0.0.1"
  hostIP: "0.0.0.0"
  hostPort: "6445"
image: rancher/k3s:v1.27.4-k3s1
network: demo-net
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 443:443
  nodeFilters:
  - loadbalancer
- port: 6445:6445 # same as `--port '8080:80@loadbalancer'`
  nodeFilters:
    - loadbalancer
# SOURCE: https://github.com/bravecobra/k8s-dev-infrastructure/blob/adb085443cffb00a69c2ddc4a415f02ef785d79a/src/clusters/k3d/devinfra-template.yaml#L2
- port: 8100:8100 # same as `--port '8100:8100@loadbalancer'`
  nodeFilters:
    - loadbalancer

#
#%{ if expose_azurite == true }
- port: 10000:10000 # same as `--port '10000:10000@loadbalancer'`
  nodeFilters:
    - loadbalancer
- port: 10001:10001 # same as `--port '10001:10001@loadbalancer'`
  nodeFilters:
    - loadbalancer
- port: 10002:10002 # same as `--port '10002:10002@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_seq == true }
- port: 5341:5341 # same as `--port '5341:5341@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_opentelemetry == true }
- port: 4317:4317 # same as `--port '4317:4317@loadbalancer'`
  nodeFilters:
    - loadbalancer
- port: 4318:4318 # same as `--port '4318:4318@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_jaeger == true }
- port: 6831:6831 # same as `--port '6831:6831@loadbalancer'`
  nodeFilters:
    - loadbalancer
- port: 6832:6832 # same as `--port '6832:6832@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rabbitmq == true }
- port: 5672:5672 # same as `--port '5672:5672@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_loki == true }
- port: 3100:3100 # same as `--port '3100:3100@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rds_mssql == true }
- port: 1433:1433 # same as `--port '1433:1433@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rds_oracle == true }
- port: 1521:1521 # same as `--port '1521:1521@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rds_mysql == true }
- port: 3306:3306 # same as `--port '3306:3306@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rds_mysql == true }
- port: 3307:3307 # same as `--port '3306:3306@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_rds_postgres == true }
- port: 5432:5432 # same as `--port '5432:5432@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_nosql_mongodb == true }
- port: 27017:27017 # same as `--port '27017:27017@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }

#%{ if expose_redis == true }
- port: 6379:6379 # same as `--port '6379:6379@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }
#%{ if expose_grafana == true }
- port: 3000:3000 # same as `--port '6379:6379@loadbalancer'`
  nodeFilters:
    - loadbalancer
#%{ endif }
# - port: 5053:53/udp
#   nodeFilters:
#   - agent:0:direct
# # https://github.com/bravecobra/k8s-e2e/blob/fe1370ae14ca9bed95523b122cca67c9e937ab44/k3s-devinfra.yaml#L2
# - port: 8100:8100 # same as `--port '8100:8100@loadbalancer'`
#   nodeFilters:
#     - loadbalancer
# - port: 8080:8080
#   nodeFilters:
#   - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5002"
  config: |
    mirrors:
      "registry.localhost":
        endpoint:
          - http://registry.local.gd:5002

volumes:
- volume: "${PWD}/storage:/var/lib/rancher/k3s/storage"
  nodeFilters:
  - server:0
  - agent:*

- volume: "$PWD/scripts/k3d-entrypoint-cilium.sh:/bin/k3d-entrypoint-cilium.sh"
  nodeFilters:
  - server:0
  - agent:*
# SOURCE: https://github.com/nxy7/k3d-cilium/blob/master/k3d.config.yaml
# - volume: /sys/fs/bpf:/sys/fs/bpf:shared # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
#   nodeFilters:
#     - server:*
#     - agent:*
# - volume: /run/cilium/cgroupv2:/run/cilium/cgroupv2:shared # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
#   nodeFilters:
#     - server:*
#     - agent:*
# SOURCE: https://github.com/defenseunicorns/uds-capability-confluence/blob/90b30c74d83f0aa4ec404a840b92a5956f921195/utils/k3d/k3d-config.yaml#L2
# - volume: /etc/machine-id:/etc/machine-id
#   nodeFilters:
#     - server:*
# - volume: /sys/fs/bpf:/sys/fs/bpf:shared
#   nodeFilters:
#     - server:*
  # --volume {{PWD}}:/var/lib/rancer/k3s/server/manifests/traefik-config.yaml@all \
  # --volume /tmp/k3dvol:/var/lib/rancher/k3s/storage@all \
hostAliases:
- ip: 127.0.0.1
  hostnames:
  - k8s.localhost
  - app.k8s.localhost
  - example.k8s.localhost
  - argocd.k8s.localhost
  - postgres.k8s.localhost
  - dbs.k8s.localhost
options:
  k3d:
    wait: true
    timeout: "360s"
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    # - arg: "--disable-network-policy"
    #   nodeFilters:
    #     - server:*
    - arg: "--debug"
      nodeFilters:
        - server:*
        - agent:*
    # - arg: "--write-kubeconfig-mode 644"
    #   nodeFilters:
    #     - server:*
    # - arg: "--write-kubeconfig ~/.kube/config"
    #   nodeFilters:
    #     - server:*
    - arg: --disable=traefik
      nodeFilters:
      - server:*
    - arg: --disable=metrics-server
      nodeFilters:
      - server:*
    # - arg: --disable-network-policy
    #   nodeFilters:
    #     - server:*
    - arg: --tls-san=localhost,registry.local.gd,127.0.0.1,registry.localhost,k8s.localhost,whoami.k8s.localhost
      nodeFilters:
      - server:*
    - arg: --kube-proxy-arg=metrics-bind-address=0.0.0.0
      nodeFilters:
      - server:*
      - agent:*
    - arg: --kube-scheduler-arg=bind-address=0.0.0.0
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=node-status-update-frequency=4s
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
      nodeFilters:
      - agent:*
    - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
      nodeFilters:
      - agent:*
    - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
      nodeFilters:
      - server:*
  # k3s: # options passed on to K3s itself
  #   extraServerArgs: # additional arguments passed to the `k3s server` command; same as `--k3s-server-arg`
  #     - --cluster-cidr=10.244.0.0/16
  #     - --service-cidr=10.96.0.0/16
  #     - --tls-san=kubernetes.k3d
  #     - --flannel-backend=none
  #     - --disable=servicelb
  #     - --disable=traefik
  #     - --disable-network-policy
    # https://github.com/chainguard-dev/actions/blob/ce8f95bff0df14286adebc33bf1617f91288caea/setup-k3d/action.yaml#L78
    # # This is needed in order to support projected volumes with service account tokens.
    # # See:
    # #   https://kubernetes.slack.com/archives/CEKK1KTN2/p1600268272383600
    # #   https://stackoverflow.com/questions/74603633/k3s-allow-unauthenticated-access-to-oidc-endpoints
    # - arg: --kube-apiserver-arg=anonymous-auth=true
    #   nodeFilters:
    #     - server:*
    # # This sets the issuer to what sigstore scaffolding expects.
    # # See also: https://github.com/k3d-io/k3d/issues/1187
    # - arg: --kube-apiserver-arg=service-account-issuer=https://kubernetes.default.svc
    #   nodeFilters:
    #     - server:*
    # - arg: --kubelet-arg=max-pods=${{ inputs.max-pods }}
    #   nodeFilters:
    #     - server:*
    #     - agent:*

    # SOURCE: https://github.com/owncloud-docker/helm-charts/blob/d183f212988cb3530d28dbe4e409aaf0b862af2a/ci/k3d-drone.yaml#L2
    # - arg: --tls-san=k3d
    #   nodeFilters:
    #     - server:*
    # - arg: --disable=servicelb
    #   nodeFilters:
    #     - server:*
    # - arg: --disable=local-storage
    #   nodeFilters:
    #     - server:*
    # - arg: --flannel-backend=none
    #   nodeFilters:
    #     - server:*
    ################################################################################
    # SOURCE: https://github.com/nxy7/k3d-cilium/blob/master/k3d.config.yaml
    ################################################################################
    # - arg: "--disable-kube-proxy"
    #   nodeFilters:
    #     - server:*
    #     - agent:*
    # - arg: "--disable=local-storage"
    #   nodeFilters:
    #     - server:*
    #     - agent:*
    # - arg: "--disable=traefik"
    #   nodeFilters:
    #     - server:*
    #     - agent:*
    - arg: "--disable=servicelb"
      nodeFilters:
        - server:*
        - agent:*
    - arg: "--flannel-backend=none"
      nodeFilters:
        - server:*
        - agent:*
    - arg: "--disable-network-policy"
      nodeFilters:
        - server:*
        - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  runtime: # runtime (docker) specific options
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
      - name: nproc
        soft: 26677
        hard: 26677
      - name: core
        soft: 26677
        hard: 26677
