apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: kube-system
spec:
  containers:
  - name: dnsutils
    image: nicolaka/netshoot
    command:
      - tail
      - -f
      - /dev/null
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
