---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/kube-system/node-feature-discovery
spec:
  project: cluster
  sources:
  - repoURL: 'https://kubernetes-sigs.github.io/node-feature-discovery/charts'
    chart: node-feature-discovery
    targetRevision: 0.15.1
    helm:
      releaseName: node-feature-discovery
      valueFiles:
        - $values/kubernetes/apps/kube-system/node-feature-discovery/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: HEAD
    path: kubernetes/apps/kube-system/node-feature-discovery
    ref: values
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
