apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini-configmap
  labels:
    app: gitea
  namespace: gitea
data:
  server: |
    SSH_PORT=3322
    DOMAIN=git.k8s.localhost
    SSH_DOMAIN=git.k8s.localhost
    ROOT_URL=https://git.k8s.localhost
  repository: |
    DEFAULT_REPO_UNITS=repo.code, repo.releases, repo.issues, repo.pulls, repo.wiki, repo.projects, repo.packages, repo.actions
    DEFAULT_BRANCH=main
  repository.pull-request: |
    DEFAULT_MERGE_STYLE=squash
    POPULATE_SQUASH_COMMENT_WITH_COMMIT_MESSAGES=true
  webhook: |
    ALLOWED_HOST_LIST=loopback,private,*.dev.kvd.studio,*.k8s.localhost
  markup: |
    ENABLED=true
  actions: |
    ENABLED=true
  security: |
    LOGIN_REMEMBER_DAYS=14
