---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # crds
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.11/deploy/crds/bundle.yaml
  - app


# SOURCE: https://www.innoq.com/en/blog/2022/07/advanced-kustomize-features/#limitlabelsandannotationstospecificresourcesorfields
labels:
- pairs:
    monitoring: prometheus
    prometheus: main

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-8"


# helmCharts:
# - name: external-secrets
#   repo: https://charts.external-secrets.io
#   version: 0.9.11
#   releaseName: external-secrets
#   namespace: kube-system
#   includeCRDs: true
#   valuesFile: app/external-secrets/values.yaml
# - name: connect
#   repo: https://1password.github.io/connect-helm-charts
#   version: 1.14.0
#   releaseName: connect
#   namespace: kube-system
#   includeCRDs: true
#   valuesFile: app/connect/values.yaml
