apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/zalando/postgres-operator/manifests
- github.com/zalando/postgres-operator/ui/manifests
namespace: databases
patches:
- path: rbac.yaml
- path: ingress.yaml
- path: clustersecretstore.yaml
