apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
    namespace: kube-system
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:/6KuxK3R0Qu/WcEQ9Lry+OQXjpItLkoYInBWFQkWpi4IvwZNINlIz4Mc6ibQ4BV3ut+o0MU5Dfj6Q5U19tW6Fi8xU/MhvHeWLzWuKFxG/6ckHS/0bwDBpkg+rMSA8f5kC6chrlf964zYiTjCceeS8yMvYZC2xgev1g2vcExGvTl+DoWowDMBmxeraJLc4ZbsyQwSYxFWapuJ+ZNDOZWemAWIb1uR/2Xp0beYDHLdZFe8wXiEFbJ0gPoS2eeh80ak+jnN1XR0iIDEYezVBiE+1EIQRYXxFOq/jIDVnOfNoxyaKRYukgtPfFjcndZoR/izjz6RjoHTCKoA6lrjt+R4KiT7kr39cPs8SbDenIcifQx2TpbZ1fAAtM7mcLSmt3EfjyZsy8g1L1uYjYsRtQ6jygiseVZAC5k3ZA+GiTNc9KSHAAXMFyyG3omuKYi5U+kH5q9U39q0RlDwYuQ9MtWhyRXTABxp493591hx+EKDGH4qlO8BDBatiuEBARnMRVQWUgkQfS7c8YkdbNVueH9Md2KQyiCqSxyAm9b+S+vRiCN664PsDNBcO7/umP5dONjR4SWkLKNxjUpPCHdrBF/7mF9irsp+FQLx3eIdZnf/Cf3vWg9epavXAx46gK5xMjOrADIZ9LplqPrllMF6GRmdLzTh2D6LrXu0otEiJrecBo7HFTWxV465DZTeG0wE0aEeaNxXdwqZpUxKtTgtQj+/97rDpzP3ngtIyN0evhROt9TdbA/foxGHEipvly4lClhk1rYkNicd9Pa8UjG//rU6h48WMAgJM/MUJec0lvxJkA4GrZESzleT2UFgJveb/anhfR5R4d9+DLTdxaxljLoMzt75FVxeI48ox0MyPBkI7N4fG53hKu9woo2y7E/329BUZgbNjMr/q/ASVLfxxqsqiL9+T6HgFJMcVLtvwmwIHK0LEkItJnInv3EBLlyRqvxsO4sdRA55BkqllwEZ5YY6XtF6WIgG+Ocar/CKpWS+W2yYVuQBmXhW6BoE0rzD4gZoVdSlu9RdM5cwKGs9Y6Irm0lJRLCYU1SosZ1kI5EQxt5XI6yFxET4LG7j2BPZucgzOc0aoOFYMAvbV5wGQQpaXtyOKMt/RZHCHxerRxgqwEgOzRyLUA3DIWK29fLgR6pkQqtM7QbOzETMeo3FTO7fyHN2flUCw4CvtFea6O5WbpRPIDCYM0i9CWi+qqVh87UAv0m4cxYMpPR8sUfGLhJC/IMtXUiCXBtrRza76twWOnFETMgOH80F9fU5U4Pk2WWE8cLwf5Ys5AXXDKTH/7WYzF5iRbVxSkVjm9kKUzqTafSvxbBLe2ZDBoqo+CmgerMNwU2aMUU1JLssfij+9mEGEiAAFCGAbSVpvw5hRzRa/fUECeiF1htzMTP5WyRExuLhpO4+wEKSVXsCwbYerVPAuemXAu6tuASnZTvddeXmkZVygADk9zh91KGHzMXe72SOhXoKglNwWciJlK48oylDc07c16eKx+OOV4ra6aGqq/qvlZh1UIj/rxeWanuWvr82g3J2hZVBUmtfcAks6L+641njM8R1A3aiBjh8GeivAcSHR6eGY061aZVbXu5RvBAZzDqg8iXOledIZfzkN/oVdlOVfgItfd8G+aCrZlFp03o9mnamxd5VSY6g+H6brNNCNHnYhP6UywMW+oVJMa07/ntrB2lYiVRk6F44GfXlOW5TWz/hOm39aCQIq0L1osVwdiJbatRgowbRAG0AUI+qMK+YgoDY5kahNJSdfCCyH0+bn58+uY68GbrETKy6IL56Y+lC4jyPYisHT/adNFSR5XDkdscxVrBpbl+VihRYuyRZvcK78VvXl6wqbeKqkBqqzIXBU8wFufhEAP+GwP3PZ0JgwXGMvlvP+TNdvlVsSzIgGqhHbCr5xt789M8ZAUJY+55u67tOph9CYXc9,iv:vIpTR522JfrYxvHA9q7NS+14na82PK8q47WFSzegeOQ=,tag:D+R35iX4Xi7l2mE2UJ4sQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6337ycedgcs2g9h5vmzlsmuuqftfkyccx4fhvv4nhpq0trz9ppshkmgat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bHN1MURRWVp0TGdsUFpI
            SzYvUnBhTFljUnBlSmpQWXBEbTQxT0JNUEFBCjBFMVB5ZDJUVTJXVDBGQytvcXg5
            Qlc4Sy8wVnRrTHNLcW44K210cGpHMWcKLS0tIDRZWVVGRnBYaTFHYUJUcjVreUZO
            UWF3Y2RhUWxtaVRYTTg3RG4vRHZZTDQK6VF8RZm2fQ4QUVXK8XLXIy7+LGO7VhzM
            4o6tt/+TJLrG4GaMXXTqsobHGL0B2ac+EM9diUXCwY0HuHDYaNR/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T22:37:49Z"
    mac: ENC[AES256_GCM,data:tv/3XOI/zv0NrQoyXZeBLzQLTPM46wz9W1AOKmXHJ4zr2vG+nNl7+7YoiVATQFRoMRQ9jNNq/NIO6MuNtEf70W8M5vY7ibcJSLZS5Yc4LstwRxzXPxSFNf+uE9rpOuoK4avYgcQvyegBysY7UHUfWPR/smMa/RzmAckRK+LTWvE=,iv:i8RvXBgeDsI96OyrBuytVyDSscCsqM3+fm1ioXTL5UE=,tag:FZpLBiOaBN88BQOEVze/yA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
