apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: kube-system
type: Opaque
stringData:
    token: eyJhbGciOiJFUzI1NiIsImtpZCI6Im12NjVpd3ppdnpuNDU3NmRzNTY3ZXV1aHV5IiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiUDcyVVREM0g0WkVUREVOWllVU0hLRjVDT1UiLCIxcGFzc3dvcmQuY29tL3Rva2VuIjoidk52VklhMDJ4Y1luWHNlZmdpNFNWaDFnSFRSZ3RyUzEiLCIxcGFzc3dvcmQuY29tL2Z0cyI6WyJ2YXVsdGFjY2VzcyJdLCIxcGFzc3dvcmQuY29tL3Z0cyI6W3sidSI6Imp0eWI2NmtseWlpZXpqMnE0bzdwdzJvNnRlIiwiYSI6NDk2fV0sImF1ZCI6WyJjb20uMXBhc3N3b3JkLmNvbm5lY3QiXSwic3ViIjoiUTRMV0tXR0hONUJWRkwyUFRUUE5LNFVQU1kiLCJpYXQiOjE3MDY0OTI5NzgsImlzcyI6ImNvbS4xcGFzc3dvcmQuYjUiLCJqdGkiOiJsajVzcnFhdXc2M2hubDJhZjdrajVvbzVucSJ9.OUs5byG2lw8A11VELFPmbhxo8OFgviobHcqbQtLcV4dZ4EBke2cFvY7zEelfg9vFgGcTTmwj2nJqfRUqddJTpQ
