---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
    argocd.argoproj.io/manifest-generate-paths: /apps/argocd/base/kube-system/external-secrets/app/connect
spec:
  project: cluster
  sources:
  - repoURL: 'https://1password.github.io/connect-helm-charts'
    chart: connect
    targetRevision: 1.14.0
    helm:
      releaseName: connect
      valueFiles:
        - $values/apps/argocd/base/kube-system/external-secrets/app/connect/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground'
    targetRevision: HEAD
    path: apps/argocd/base/kube-system/external-secrets/app/connect
    ref: values
  destination:
    # name: in-cluster
    namespace: kube-system
    name: in-cluster
  # syncPolicy:
  #   automated:
  #     prune: true
  #   syncOptions:
  #     - CreateNamespace=true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
      # Needed because our kubectl apply exceeds thresholds
      # EXAMPLE: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
      # SOURCE: https://github.com/prometheus-operator/prometheus-operator/issues/4355
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: -1  # Max number of allowed sync retries
      backoff:
        duration: 20s # Retry backoff base duration. Input needs to be a duration (e.g. 2m, 1h) (default 5s)
        factor: 2 # Factor multiplies the base duration after each failed retry (default 2)
        maxDuration: 15m # Max retry backoff duration. Input needs to be a duration (e.g. 2m, 1h) (default 3m0s)
  # SOURCE: https://github.com/argoproj/argo-cd/issues/11074
