---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        k3d: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: kube-system
