# https://github.com/goabout/kustomize-sopssecretgenerator
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: external-secrets-generator
#####################################################################################
# NOTE: in kustomize-sops this is the config value
# # replace the base secret data/stringData values with these encrypted data/stringData values
# kustomize.config.k8s.io/behavior: create
#####################################################################################
# SOURCE: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#generator-options
# Generator options
# Regardless of how it is built, a plugin can adjust the generator options for the resources it emits by setting one of the following internal annotations.
#
# NOTE: These annotations are local to kustomize and will not be included in the final output.
#
# kustomize.config.k8s.io/needs-hash
#
# Resources can be marked as needing to be processed by the internal hash transformer by including the needs-hash annotation. When set valid values for the annotation are "true" and "false" which respectively enable or disable hash suffixing for the resource. Omitting the annotation is equivalent to setting the value "false".
#
# Hashes are determined as follows:
#
# For ConfigMap resources, hashes are based on the values of the name, data, and binaryData fields.
# For Secret resources, hashes are based on the values of the name, type, data, and stringData fields.
# For any other object type, hashes are based on the entire object content (i.e. all fields).
#####################################################################################
behavior: create
disableNameSuffixHash: true
files:
  # - accessToken.sops.yaml
  # - 1passwordCredentials.sops.yaml
  - accessToken.sops.yaml
  # - base/kube-system/external-secrets/app/connect/accessToken.sops.yaml
  - 1passwordCredentials.sops.yaml
  # - base/kube-system/external-secrets/app/connect/1passwordCredentials.sops.yaml
