# https://github.com/goabout/kustomize-sopssecretgenerator
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: external-secrets-generator
files:
  # - accessToken.sops.yaml
  # - 1passwordCredentials.sops.yaml
  - apps/argocd/base/kube-system/external-secrets/app/connect/accessToken.sops.yaml
  - apps/argocd/base/kube-system/external-secrets/app/connect/1passwordCredentials.sops.yaml
