---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bossjones/k3d-playground/main/schema/external-secrets/v0.9.11/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudnative-pg # name of the k8s Secret to be created
  data:
  - secretKey: source-key1
    remoteRef:
      key: databases/cloudnative-pg
      property: cloudnative-pg
# accesskey: admin
#   secretkey: password
# SOURCE: https://github.com/cloudnative-pg/cloudnative-pg/blob/89a46c9904f6220e06a28f463697b98ba90bc746/docs/src/bootstrap.md?plain=1#L330
---
apiVersion: v1
data:
  username: YXV0aGVudGlr
  password: OGVkRjZzUlFqeA==
kind: Secret
metadata:
  name: authentik-secret
  namespace: databases
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: postgres-superuser
  namespace: databases
type: kubernetes.io/basic-auth
