apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: databases
stringData:
  source-key1: "{\"POSTGRES_SUPER_USER\": \"authentik\",  \"POSTGRES_SUPER_PASS\": \"8edF6sRQjx\",  \"AWS_ACCESS_KEY_ID\": \"admin\",  \"AWS_SECRET_ACCESS_KEY\": \"password\",  \"username\": \"authentik\",  \"password\": \"8edF6sRQjx\"}" # Needs to be a JSON
  # source-key2: bar  # Could be a plain string
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudnative-pg-pushsecret
  namespace: databases
spec:
  refreshInterval: 15s
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudnative-pg
  data:
    - match:
        secretKey: source-key1
        remoteRef:
          remoteKey: databases/cloudnative-pg
