---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app.yaml
  - postgres
  - minio
  - httpbin
  - webhooks
  - dex
  # - quick-start-postgres.yaml
  - coinflip-recursive.yaml
  - containerset.yaml
  - hello-world.yaml
  - http-template.yaml
  - k8s-resource-output.yaml
  # - httpbin.yaml

namespace: argo

patches:
# - path: patch-securitycontext.yaml
#   target:
#     kind: Deployment
- path: remove-livenessprobe.yaml
  target:
    kind: Deployment
    name: workflow-controller
