apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend # name of the SecretStore (or kind specified)
    kind: ClusterSecretStore
  target:
    name: test # name of the k8s Secret to be created
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/foo
      property: hello
