---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  # annotations:
  #   notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
  #   argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/networking/ingress-nginx
spec:
  project: cluster
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx/'
    chart: ingress-nginx
    targetRevision: 4.9.0
    helm:
      releaseName: ingress-nginx
      valueFiles:
        # - $values/kubernetes/apps/networking/ingress-nginx/app/values.yaml
        - $values/apps/argocd/base/core/ingress-nginx/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground.git'
    targetRevision: main
    path: apps/argocd/base/core/ingress-nginx
    ref: values
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
