commonLabels:
  prometheus: main

controller:
  # -- Configures the ports that the nginx-controller listens on
  containerPort:
    http: 80
    https: 443
    argo: 2746
    ssh: 22
  replicaCount: 1
  allowSnippetAnnotations: true
  extraEnvs:
    - name: TZ
      value: America/New_York
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    # -- Labels to be added to both controller services.
    labels:
      prometheus: main
  ingressClassResource:
    default: true
  config:
    proxy-body-size: 0
    proxy-buffer-size: "16k"
    ssl-protocols: "TLSv1.3 TLSv1.2"
    use-forwarded-headers: "true"
    client-body-buffer-size: "100M"
    # client-body-timeout: 120
    # client-header-timeout: 120
    client-body-timeout: 3600
    client-header-timeout: 3600
    enable-brotli: "true"
    enable-real-ip: "true"
    forwarded-for-header: "CF-Connecting-IP"
    custom-http-errors: 404,403
    hsts-max-age: "31449600"
    keep-alive-requests: 10000
    keep-alive: 120
    large-client-header-buffers: "4 16k"
  extraArgs:
      default-ssl-certificate: "kube-system/tls-secret"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: kube-system
      namespaceSelector:
        any: true
defaultBackend:
  enabled: true
  image:
    repository: ghcr.io/tarampampam/error-pages
    tag: 2.26.0
  extraEnvs:
    - name: TEMPLATE_NAME
      value: ghost
    - name: SHOW_DETAILS
      value: "true"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["ingress-nginx"]
                - key: app.kubernetes.io/component
                  operator: In
                  values: ["default-backend"]
            topologyKey: kubernetes.io/hostname


# -- TCP service key-value pairs
## Ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/exposing-tcp-udp-services.md
##
tcp:
  2746: "argo/argo-workflows-server:2746"
#  8080: "default/example-tcp-svc:9000"

# -- UDP service key-value pairs
## Ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/exposing-tcp-udp-services.md
##
udp:
  53: "kube-system/kube-dns:53"

# -- Prefix for TCP and UDP ports names in ingress controller service
## Some cloud providers, like Yandex Cloud may have a requirements for a port name regex to support cloud load balancer integration
portNamePrefix: ""
# -- (string) A base64-encoded Diffie-Hellman parameter.
# This can be generated with: `openssl dhparam 4096 2> /dev/null | base64`
## Ref: https://github.com/kubernetes/ingress-nginx/tree/main/docs/examples/customization/ssl-dh-param
dhParam: ""
