---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  # annotations:
  #   notifications.argoproj.io/subscribe.on-deployed-github.pushover: ui6cxf78gwxa6n93zkwddw1g8s3yio
  #   argocd.argoproj.io/manifest-generate-paths: /kubernetes/apps/kube-system/cilium
  labels:
    argocd.argoproj.io/instance: cilium
spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: cilium-ca
      jsonPointers:
      - /data/ca.crt
      - /data/ca.key
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
  project: cluster
  sources:
  - repoURL: 'https://helm.cilium.io/'
    chart: cilium
    targetRevision: 1.14.6
    helm:
      valueFiles:
        - $values/apps/argocd/base/monitoring/cilium/app/values.yaml
  - repoURL: 'https://github.com/bossjones/k3d-playground.git'
    targetRevision: main
    path: apps/argocd/base/monitoring/cilium
    ref: values
  destination:
    # server: "https://kubernetes.default.svc"
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
