apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: debug-pause
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: argoproj/argosay:v2
        env:
          - name: ARGO_DEBUG_PAUSE_AFTER
            value: 'true'
