podAnnotations:
  secret.reloader.stakater.com/reload: authentik-secret, authentik-db-secret,authentik-redis-secret

authentik:
  log_level: debug
  secret_key: 5up3r53cr37K3y
  email:
    port: 587
    use_tls: true
  # SOURCE: https://github.com/jemand771/server-deployments/blob/061ad9a8294c66973ff958272404a2f515cb4fea/_infrastructure/authentik/values.yaml
  # email:
  #   host: mailc.jemand771.net
  #   port: 587
  #   username: sso@jemand771.net
  #   use_tls: true
  #   from: sso@jemand771.net
  error_reporting:
    enabled: true
    send_pii: false
  redis:
    host: "authentik-redis.security.svc.cluster.local"
    password: ""

envFrom:
  - secretRef:
      name: authentik-secret
  - secretRef:
      name: authentik-db-secret

envValueFrom:
  AUTHENTIK_REDIS__PASSWORD:
    secretKeyRef:
      name: authentik-redis-secret
      key: AUTHENTIK_REDIS_PASSWORD

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    # external-dns.alpha.kubernetes.io/target: ingress-ext.bjw-s.dev
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: "authentik.k8s.localhost"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "authentik.k8s.localhost"

postgresql:
  enabled: false

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: false
