podAnnotations:
  secret.reloader.stakater.com/reload: authentik-secret, authentik-db-secret,authentik-redis-secret

authentik:
  log_level: info
  email:
    port: 587
    use_tls: true
  error_reporting:
    enabled: false
    send_pii: false
  redis:
    host: "authentik-redis.security.svc.cluster.local"
    password: ""

envFrom:
  - secretRef:
      name: authentik-secret
  - secretRef:
      name: authentik-db-secret

envValueFrom:
  AUTHENTIK_REDIS__PASSWORD:
    secretKeyRef:
      name: authentik-redis-secret
      key: AUTHENTIK_REDIS_PASSWORD

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    # external-dns.alpha.kubernetes.io/target: ingress-ext.bjw-s.dev
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: "authentik.k8s.localhost"
      paths:
        - path: /
  tls:
    - hosts:
        - "authentik.k8s.localhost"

postgresql:
  enabled: false

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: false
