apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/projects/core.yaml
- base/projects/cluster.yaml
- base/projects/monitoring.yaml
- base/projects/networking.yaml
- base/projects/apps.yaml
# - base/monitoring/cilium/app/app.yaml
- base/core/ingress-nginx/app/app.yaml
# - base/core/nginx.yaml
- base/core/argocd.yaml
- base/core/ingress.yaml
# - base/core/allow-all-egress.yaml
- base/apps/example.yaml
- base/apps/template.yaml
- base/utilities/zalando.yaml
- base/utilities/reloader.yaml
- base/utilities/reflector.yaml
# - base/utilities/descheduler.yaml
- base/monitoring/kube-prometheus-stack/app/app.yaml
- base/monitoring/metrics-server/app/app.yaml
- base/monitoring/rancher/app/app.yaml
- base/monitoring/loki-distributed/app/app.yaml
- base/monitoring/vector/app/app.yaml
- base/monitoring/k8s-event-logger/app/app.yaml
- base/monitoring/argo-rollouts/app/app.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml
# - base/core/role_prometheus-k8s.yaml
# - base/core/rolebinding_prometheus-k8s.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests


namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.8.0

commonAnnotations:
  reloader.stakater.com/auto: "true"

patches:
- path: overlay/argocd-svc.yaml
- path: overlay/argocd-rbac.yaml
- path: overlay/argocd-cm.yaml
- path: overlay/argocd-cr.yaml
- path: overlay/argocd-cmd-params-cm.yaml
- path: overlay/argocd-server-role.yaml
- path: overlay/delete-np-argocd-redis-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-redis-network-policy
- path: overlay/delete-np-argocd-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-server-network-policy
- path: overlay/delete-np-argocd-dex-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-dex-server-network-policy
- path: overlay/delete-np-argocd-repo-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-repo-server-network-policy
- path: overlay/delete-np-argocd-notifications-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-notifications-controller-network-policy
- path: overlay/delete-np-argocd-application-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-application-controller-network-policy
- path: overlay/delete-np-argocd-applicationset-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-applicationset-controller-network-policy
