apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.9/manifests/install.yaml
- base/projects/core.yaml
- base/projects/cluster.yaml
- base/projects/monitoring.yaml
- base/projects/networking.yaml
- base/projects/apps.yaml
- base/monitoring/kube-prometheus-stack/app/app.yaml
- base/kube-system/external-secrets/app/external-secrets/app.yaml
- base/kube-system/external-secrets/app/connect/app-connect.yaml
- base/monitoring/thanos-minio/app/app.yaml
- base/monitoring/thanos/app/app.yaml

- base/core/ingress-nginx/app/app.yaml

- base/core/argocd.yaml
- base/core/ingress.yaml

- base/utilities/zalando.yaml
- base/apps/example.yaml
- base/apps/template.yaml
- base/utilities/reloader.yaml
- base/utilities/reflector.yaml
# - base/utilities/descheduler.yaml

- base/monitoring/metrics-server/app/app.yaml
# - base/monitoring/rancher/app/app.yaml

- base/monitoring/vector/app/app.yaml
- base/monitoring/k8s-event-logger/app/app.yaml
- base/monitoring/argo-rollouts/app/app.yaml
- base/monitoring/loki/app/app.yaml
- base/monitoring/prometheus-adapter/app/app.yaml
- base/monitoring/cert-manager/app/app.yaml

# - base/gitops/argo-workflows/app/app.yaml
- base/monitoring/hajimari/app/app.yaml
# - base/monitoring/gethomepage/app/app.yaml
- base/monitoring/k8s-ephemeral-storage-metrics/app/app.yaml
- base/monitoring/kubernetes-dashboard/app/app.yaml
# - base/gitea/gitea/app/app.yaml
- base/identity/authentik-redis/app/app.yaml
- base/database/cloudnative-pg/app/app.yaml
- base/identity/authentik/app/app.yaml
# - base/core/role_prometheus-k8s.yaml
# - base/core/rolebinding_prometheus-k8s.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests


namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.8.9

commonAnnotations:
  reloader.stakater.com/auto: "true"

# generators:
# - base/core/SopsSecretGenerator.yaml

patches:
- path: overlay/argocd-svc.yaml
- path: overlay/argocd-rbac.yaml
- path: overlay/argocd-cm.yaml
- path: overlay/argocd-cr.yaml
- path: overlay/argocd-cmd-params-cm.yaml
- path: overlay/argocd-server-role.yaml
# - path: overlay/add-resources-argocd-repo-server.yaml
- path: overlay/delete-np-argocd-redis-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-redis-network-policy
- path: overlay/delete-np-argocd-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-server-network-policy
- path: overlay/delete-np-argocd-dex-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-dex-server-network-policy
- path: overlay/delete-np-argocd-repo-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-repo-server-network-policy
- path: overlay/delete-np-argocd-notifications-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-notifications-controller-network-policy
- path: overlay/delete-np-argocd-application-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-application-controller-network-policy
- path: overlay/delete-np-argocd-applicationset-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-applicationset-controller-network-policy
- path: overlay/patch-configmap-argocd-ssh-known-hosts-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-ssh-known-hosts-cm
- path: overlay/patch-argocd-cm-secrets.yaml


- target:
    # version: v1
    group: apps
    kind: Deployment
    name: argocd-repo-server
  # Strip
  # Stripping is specified by the "-"" chomping indicator. In this case, the final line break and any trailing empty lines are excluded from the scalar's content.
  patch: |-
    # ##########################################################################
    # SOURCE: https://github.com/jimmy-ungerman/pork3s
    # ##########################################################################
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: XDG_CONFIG_HOME
        value: /.config
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SOPS_AGE_KEY_FILE
        value: /.config/sops/age/key.txt

    # ##########################################################################
    # Further configuration by https://github.com/goabout/kustomize-sopssecretgenerator/blob/master/docs/argocd.md
    # SOURCE: https://github.com/goabout/kustomize-sopssecretgenerator/blob/master/docs/argocd.md for sopsSecretsGenerator.yaml
    # ##########################################################################
    # # SOURCE: https://github.com/aggregion/argo-base/blob/03b6e39bd94f6338fe446f736a0626b7a966b455/install/helm-secrets/argocd-repo-server.yaml#L110
    # SOURCE: https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration
    # ##########################################################################
    # #
    # ENVS FOR MAIN CONTAINER
    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_PLUGINS
    #     value: /custom-tools/helm-plugins/

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_CURL_PATH
    #     value: /custom-tools/curl

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_CURL_PATH
    #     value: /usr/bin/curl

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_SOPS_PATH
    #     value: /custom-tools/sops

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_VALS_PATH
    #     value: /custom-tools/vals

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_KUBECTL_PATH
    #     value: /custom-tools/kubectl

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_BACKEND
    #     value: sops

    # # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
    #     value: "false"

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
    #     value: "true"

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
    #     value: "false"

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_WRAPPER_ENABLED
    #     value: "true"

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_HELM_PATH
    #     value: /usr/local/bin/helm

    # - op: add
    #   path: /spec/template/spec/containers/0/env/-
    #   value:
    #     name: HELM_SECRETS_LOAD_GPG_KEYS
    #     # Multiple keys can be separated by space
    #     value: /helm-secrets-private-keys/key.asc

    # VOLUMES
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: custom-tools
        emptyDir: {}

    # pork3s
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: sops-age
        secret:
          secretName: sops-age

    # - op: add
    #   path: /spec/template/spec/volumes/-
    #   value:
    #     name: helm-secrets-private-keys
    #     secret:
    #       secretName: helm-secrets-private-keys

    ##############################################################################################################
    # VOLUME MOUNTS FOR MAIN CONTAINER
    ##############################################################################################################
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        mountPath: /custom-tools
        name: custom-tools

    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        mountPath: /usr/local/sbin/helm
        subPath: helm
        name: custom-tools

    # - op: add
    #   path: /spec/template/spec/containers/0/volumeMounts/-
    #   value:
    #     mountPath: /helm-secrets-private-keys/
    #     name: helm-secrets-private-keys


    ##############################################################################################################
    # bossjones via pork3s
    ##############################################################################################################

    # - op: add
    #   path: /spec/template/spec/containers/0/volumeMounts/-
    #   value:
    #     mountPath: /usr/local/bin/kustomize
    #     name: custom-tools
    #     subPath: kustomize

    # add SopsSecretGenerator plugin
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        mountPath: /.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator
        name: custom-tools
        subPath: SopsSecretGenerator

    # - op: add
    #   path: /spec/template/spec/containers/0/volumeMounts/-
    #   value:
    #     mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
    #     name: custom-tools
    #     subPath: ksops

    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        mountPath: /.config/sops/age
        name: sops-age

    # INIT CONTAINER
    - op: add
      path: /spec/template/spec/initContainers/-
      value:
        name: download-tools
        # image: registry.aggregion.com/helm-secrets-argocd:0.0.1
        # image: viaductoss/ksops:v4.3.1
        image: docker.io/bossjones/argocd-custom-tools:0.0.5
        # image: docker.io/bossjones/argocd-custom-tools:0.0.1
        imagePullPolicy: Always
        # command: [sh, -ec]
        command: ["/bin/sh", "-c"]
        # args:
        # - 'echo "Installing KSOPS..."; mv /usr/local/bin/ksops /custom-tools/; mv /usr/local/bin/kustomize /custom-tools/; echo "Done.";'
        args:
        # mv /usr/local/bin/kustomize /custom-tools/;
        - echo "Installing goabout kustomize sops...";
          set -e;
          set -x;
          cp -av /custom-tools-tmp/* /custom-tools/;
          set +x;
          echo "Done.";
        # args:
        # - echo "Installing goabout kustomize sops...";
        #   set -e;
        #   set -x;
        #   get_os="$(uname -s | tr '[:upper:]' '[:lower:]')";
        #   get_arch="$(uname -m | tr '[:upper:]' '[:lower:]')";
        #   VERSION=1.6.0 PLATFORM="$(uname -s | tr '[:upper:]' '[:lower:]')" ARCH="arm64";
        #   wget -O /custom-tools/SopsSecretGenerator https://github.com/goabout/kustomize-sopssecretgenerator/releases/download/v${VERSION}/SopsSecretGenerator_${VERSION}_${PLATFORM}_${ARCH};
        #   chmod -v +x /custom-tools/SopsSecretGenerator;
        #   mv /usr/local/bin/kustomize /custom-tools/;
        #   set +x;
        #   echo "Done.";
        env:
        - name: HELM_SECRETS_VERSION
          value: "4.4.2"
        - name: KUBECTL_VERSION
          value: "1.27.4"
        - name: VALS_VERSION
          value: "0.24.0"
        - name: SOPS_VERSION
          value: "3.8.1"
        - name: MAIN_PATH
          value: "/custom-tools"
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

    # ##########################################################################
    # # SOURCE: https://github.com/aggregion/argo-base/blob/03b6e39bd94f6338fe446f736a0626b7a966b455/install/helm-secrets/argocd-repo-server.yaml#L110
    # ##########################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    ######################################################################
    # - op: add
    #   path: /spec/template/metadata/labels/egress.home.arpa~1apiserver
    #   value: allow
    # - op: add
    #   path: /spec/template/metadata/labels/egress.home.arpa~1world
    #   value: allow
    # - op: add
    #   path: /spec/template/metadata/labels/egress.home.arpa~1kubedns

labels:
- pairs:
    monitoring: prometheus
    prometheus: main
