apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/projects/core.yaml
- base/projects/cluster.yaml
- base/projects/monitoring.yaml
- base/projects/networking.yaml
- base/projects/apps.yaml
- base/core/nginx.yaml
- base/core/argocd.yaml
- base/core/ingress.yaml
- base/core/allow-all-egress.yaml
- base/apps/example.yaml
- base/apps/template.yaml
- base/utilities/zalando.yaml
- base/utilities/reloader.yaml
- base/utilities/reflector.yaml
- base/utilities/descheduler.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests
# - https://github.com/argoproj-labs/argocd-extensions/tree/main/manifests


namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.8.0

commonAnnotations:
  reloader.stakater.com/auto: "true"
patches:
- path: overlay/argocd-svc.yaml
- path: overlay/argocd-rbac.yaml
- path: overlay/argocd-cm.yaml
- path: overlay/argocd-cr.yaml
- path: delete-np-argocd-redis-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-redis-network-policy
- path: delete-np-argocd-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-server-network-policy
- path: delete-np-argocd-dex-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-dex-server-network-policy
- path: delete-np-argocd-repo-server-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-repo-server-network-policy
- path: delete-np-argocd-notifications-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-notifications-controller-network-policy
- path: delete-np-argocd-application-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-application-controller-network-policy
- path: delete-np-argocd-applicationset-controller-network-policy.yaml
  target:
    kind: NetworkPolicy
    name: argocd-applicationset-controller-network-policy
